# Generated by Django 4.1.5 on 2023-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='security_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
