# Generated by Django 4.1.5 on 2023-02-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.IntegerField()),
                ('crypto_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_wallets.cryptowallet')),
            ],
        ),
    ]
