# Generated by Django 4.1.5 on 2023-03-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0002_cryptowallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='address',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
