# Generated by Django 4.1.5 on 2023-03-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0003_alter_cryptowallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='output_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='received',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='spent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='unspent_output_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
