# Generated by Django 4.1.5 on 2023-03-21 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_wallets', '0004_cryptowallet_output_count_cryptowallet_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowallet',
            unique_together={('user', 'cryptocurrency', 'address')},
        ),
    ]
