# Generated by Django 4.1.5 on 2023-03-03 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoexchangeaccount',
            name='how_much_money_on_it',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
