# Generated by Django 4.1.5 on 2023-03-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0002_cryptoexchangeaccount_how_much_money_on_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoexchangeaccount',
            name='how_much_money_on_it',
        ),
    ]
