# Generated by Django 4.1.5 on 2023-03-06 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0003_remove_cryptoexchangeaccount_how_much_money_on_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoexchangeaccount',
            name='balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
