# Generated by Django 4.1.5 on 2023-03-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0004_cryptoexchangeaccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoexchangeaccount',
            name='balance',
        ),
    ]
